### ISSUE TITLE
Dark mode a little jarring with lots of bright elements unaffected by dark mode style changes

### ISSUE THREAD

**Issue by PersonalPalimpsest** [rangelojc/mh-dark-mode#3]
As a bit of a blanket generic fix, applying this to the css of the entire page helped smooth things out for me:
`filter: contrast(.8) brightness(.8) saturate(.8);`

**Comment by rangelojc** [comment]
We are already applying some sort of filter like this one especially on camp page. Unfortunately applying it everywhere might be received with mixed feelings, so I am skipping any dimming filters for now.

We could make a toggle to activate a filter like this for those who want to, but we have no plans yet to create a script for advanced dark mode customization, or any script at all.
